name: CI check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install
      run: make install

    - name: build
      run: make build

    - name: test
      run: make coverage

    - name: lint
      run: make lint

    - uses: paambaati/codeclimate-action
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: make coverage