name: CI check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install
      run: make install

    - name: build
      run: make build

    - name: test
      run: make test

    - name: lint
      run: make lint
